apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
    name: minio-secrets
spec:
    provider: azure
    parameters:
        keyvaultName: { ? { .Values.keyVault.name } }
        tenantId: { ? { .Values.keyVault.tenantId } }
        objects: |
            array:
              - |
                objectName: minio-access-key
                objectType: secret
              - |
                objectName: minio-secret-key
                objectType: secret
