deploymentMode: SimpleScalable

loki:
  auth_enabled: false
  useTestSchema: true
  storage:
    type: s3

    bucketNames:
      chunks: logs-dev
      ruler: logs-dev
      admin: logs-dev

    s3:
      endpoint: http://minio.logging.svc.cluster.local:9000
      s3ForcePathStyle: true
      region: us-east-1

  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      value: minioadmin
    - name: AWS_SECRET_ACCESS_KEY
      value: minioadmin123

write:
  replicas: 1

read:
  replicas: 1

backend:
  replicas: 1
