apiVersion: v2
name: logging-stack
description: Umbrella Helm chart for MinIO + Loki + Alloy in a single AKS cluster
type: application
version: 1.0.0

dependencies:
  - name: minio
    version: "5.2.0"
    repository: "https://charts.min.io/"

  - name: loki
    version: "6.49.0"
    repository: "https://grafana.github.io/helm-charts"

  - name: alloy
    version: "0.7.0"
    repository: "https://grafana.github.io/helm-charts"
